### ISSUE TITLE
gui debugger

### ISSUE THREAD

**Issue by koke2c95** [trigger-death/TriggersTools.CatSystem2#1]
game debugger like readme?

**Comment by koke2c95** [comment]
oh, that's CatSystem2 self debugger, and need all decrypt Int's Packget ...

**Comment by trigger-segfault** [comment]
Alright, I've started to sort out the information needed to actually setup debug mode if you're interested.

Decrypting the archives isn't required anymore, but some features *will* work better if the archives are extracted.

*I apologize that this info is a bit jumbled, my notes and tests over the last few months have been very scattered and unorganized.*

### Requirements

1. `cs2_debug_key.dat` *(contains random data unique to each game)* **(i)**
2. Locale Emulator, *(or Japanese system locale)*
3. Extract `scene.dat` to a new folder: `scene/` *(enables script selection+navigation)*
4. Find the `<wndmenu>` option in `startup.xml`, set the value to **1**. *(enable menu bar, required for some features)* **(iii)**
5. Add these debug keybinds to `KEYCUSTOMIZE` list in `startup.xml` *(some features can only be accessed with keybinds)* **(iii)**  (TODO: Link xml debug keys from CS2 patcher in this repo)
6. If you have a Grisaia game,  the `startup.xml` likely contains an invalid comment that invalidates all settings defined after that point(?)  Look for `<!--` with a `-->` on the next line. Removing the first *should* fix this.

**Archives that DO NOT need to be extracted:**

*(archives not listed here are unconfirmed)*

* `kcs.int`
* `mot.int`
* `export.int`
* `image.int` *(some games use slightly different names, they will be defined in `startup.xml`)*
* `pcm_*.int`
* `bgm.int`, `bgmv.int`
* `se.int`, `hse.int`


**Notes:**

* (i) These files can be generated with commonly known encryption methods used by CS2, using the `V_CODE` (1), which can be found in `startup.xml` and sometimes the cs2.exe binary. (TODO: link info)
* (iii) if you already have save data, you *may* need to delete `setup.xml` from your game save folder.

### Todo

* **Link to:** xml debug keybinds, Locale Emulator, Wiki Pages documenting: Key Files (like the debug file), Debug Mode, Official CatSystem 2 manual (jp), Official CatSystem2 toolset (where you can fiddle with a working debug mode)


If you have any issues, need something explained in more detail, or help using the engines debug mode, then let me know.  The debug mode feature can be quite awkward. — Later I can also write up a proper program/script for generating the the debug key file data.

And as it's not present in requirements, patching is no longer necessary.  Patching the game exe was only done to workaround `cs2_debug_key.dat` being specific to each game. (Similarly, some other old requirements were only needed because of the patch-based solution)

I will try to finish writing up what info I've collected in the next few days *(hopefully)*.  I always seem to find myself doing this at 1am

**Comment by trigger-segfault** [comment]
If you don't mind, I'll also be reopening this issue, just to make the information more accessible (and for new discussion) until it gets added to the repo's wiki. 🎉

**Comment by koke2c95** [comment]
thank your reply !!  but i had delete these tools. and now i  no time to redownload try it 
sorry :(

**Comment by trigger-segfault** [comment]
That's okay, I'll still throw what I've currently got up on the wiki later.  👍 
And I apologize, reopening a user-closed issue was a bit rude of me.
