### ISSUE TITLE
Multiple files inside .hg3

### ISSUE THREAD

**Issue by Cerzs** [trigger-death/TriggersTools.CatSystem2#4]
Hello.

I'm trying to convert a single .hg3 that contains multiple images inside. The documentation says that adding @ to the beginning of the layer (PSD) results in all of them being copied, but I have not been able to. Can you tell me what I'm doing wrong?

Here's a [sample](https://cdn.discordapp.com/attachments/687043665289412705/851570856814968852/sys_config.hg3) of the original file.

Thank you.

**Comment by AtomCrafty** [comment]
Ahaha, that file is from Rinko, isn't it? :D
This is what the layer structure looks like for that particular file:
![image](https://user-images.githubusercontent.com/4553050/121092396-c4ec6200-c7eb-11eb-848c-c8b82153dd20.png)
Every layer starting with an @ symbol becomes a layer in the hg3 file, its index is the sum of the numbers in parentheses on the path from the document root to that layer. The string in brackets at the top decides the name of the generated file.

So the layer `(900)ヘッダーボタン`/`(30)システム`/`@(3)押下` in this case would be exported as layer 933 in file `sys_config.hg3`.

I believe these are the converter settings I used for Rinko:
![image](https://user-images.githubusercontent.com/4553050/121092845-7a1f1a00-c7ec-11eb-8472-6f255d9c21c4.png)

**Comment by tbhoang12** [comment]
hi I had downloaded the tool you said ,when I click on the exe to start it gave me error
![Error hgx2bmp tool 7_9_2021 , 1_33_25 AM](https://user-images.githubusercontent.com/76590480/124973566-e7c19e80-e055-11eb-9d1f-18e7da589705.png)
I'm using win7 32bit and here is the [sys_title.hg3](https://drive.google.com/file/d/1veyOyDQJK2paITn-eT29Ma0nRhNiqTxW/view?usp=sharing) in Japanese contains menu icons I need to mod ,please show me step by step because I don't know how to coding and stuffs (if you can make an easy tool for newbie fan translator like CatSceneEditor script edit tool it would be great)
![SKMK Touka with kids in townScreenshot - 7_7_2021 , 5_38_15 AM](https://user-images.githubusercontent.com/76590480/124974869-869aca80-e057-11eb-816f-049d29c8ca0a.png)

**Comment by trigger-segfault** [comment]
For context, I redirected @tbhoang12 here since they were having the same difficulty building an HG3 from extracted images.

Individual frames are GARbro-extracted, so they need to be extracted *again* while restoring the removed transparency border.

***
You can grab the zlib1.dll [here](https://github.com/trigger-segfault/TriggersTools.CatSystem2/blob/master/libs/zlib/bin/x86/zlib1.dll), and place it in the same folder as the tool. (This is the dll needed to handle decompressing the image formats).

Also I think you'll need to use `hgx2bmp.exe` (not the no expand one).

Additionally, this is a command line tool. However you can operate it by dragging the HG3 file on-top of the executable.
***
I'm not sure how well I can provide detailed instructions though >.>

**Comment by tbhoang12** [comment]
ok,now after fixed that "zlib1.dll is missing error" >> I dragged and drop the sys_title.hg3 (which I used GarBro to extract from image01.int file ) into the hgx2bmp.exe like you instructed
I got a black BMP image file ? Now what do I have to do next ?
![SKMK Sys_title extracted black BMP 7_9_2021 , 8_35_59 AM](https://user-images.githubusercontent.com/76590480/125011371-866bf080-e092-11eb-90f7-fdeb75669613.png)


> For context, I redirected @tbhoang12 here since they were having the same difficulty building an HG3 from extracted images.
> 
> Individual frames are GARbro-extracted, so they need to be extracted _again_ while restoring the removed transparency border.
> 
> You can grab the zlib1.dll [here](https://github.com/trigger-segfault/TriggersTools.CatSystem2/blob/master/libs/zlib/bin/x86/zlib1.dll), and place it in the same folder as the tool. (This is the dll needed to handle decompressing the image formats).
> 
> Also I think you'll need to use `hgx2bmp.exe` (not the no expand one).
> 
> Additionally, this is a command line tool. However you can operate it by dragging the HG3 file on-top of the executable.
> 
> I'm not sure how well I can provide detailed instructions though >.>
